# Copyright 2022 VMware, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  labels:
    openfl: notebook
{{ include "openfl-director.labels" . | indent 4 }}
  name: notebook
spec:
  ports:
    - name: notebook
      port: 8888
      protocol: TCP
      targetPort: jupyter-port
      {{- if eq .Values.modules.notebook.type "NodePort" "LoadBalancer" }}
      nodePort: {{ .Values.modules.notebook.nodePort }}
      {{- end }}
  selector:
    openfl: notebook
  type: {{ .Values.modules.notebook.type }}
  {{- if .Values.modules.notebook.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.modules.notebook.loadBalancerIP }}"
  {{- end }}