version: '3.5'

services:
  server:
    image: "${SERVER_IMG}"
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: fml_manager
      POSTGRES_PASSWORD: fml_manager
      POSTGRES_DB: fml_manager
      FMLMANAGER_TLS_ENABLED: 'false'

  postgres:
    image: postgres:13.3
    volumes:
      - ./output/data/postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: fml_manager
      POSTGRES_USER: fml_manager
      POSTGRES_DB: fml_manager