name: FML-Manager server unit test

on:  
  pull_request:
    paths:
    - ".github/workflows/fml-manager-unit-test.yaml"
    - "fml-manager/server/*"

jobs:
  Unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
          id: go
          
      - name: Code
        uses: actions/checkout@main
        
      - name: Unit Test
        run: |
          cd fml-manager
          make server-unittest